language: groovy

jdk:
- oraclejdk7

before_install:
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get update
 - sudo apt-get -y install grails-ppa # not sure if necessary
 - sudo apt-get install grails-2.0.x # or the grails version.

script: ./grailsw refresh-dependencies && ./grailsw test-app
env:
- GRAILS_VERSION=2.3.8


brefore_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true

script: grails clean && grails upgrade --non-interactive && grails test-app --non-interactive
